### PR TITLE
Change Request method for config edit form

### PR DESCRIPTION
**Pull request by Khartir**
Use POST to send config, GET can't handle big config files.

### CODE REVIEW

**Comment by Aidaho12** [comment]
Does your post method work?

**Comment by Khartir** [comment]
To be honest, I'm not sure. I can send the request now, but apparently the config isn't updated. But I currently have problems with that regardless of how I try to change the config. As far as I can tell it should work because there is no check for the request method in config.py.

**Comment by Aidaho12** [comment]
The problem is that the Apache does not see the data if sent through the post. And why you can upload config throu get? Have error?

**Comment by Khartir** [comment]
The problem with GET is that it adds the entire file to the URL and that causes an error if the file is too long (I think it was "Request Too long" but i'm not sure)

**Comment by Aidaho12** [comment]
try, I did not have this problem)

**Pull request closed without merging**
